// Code generated by "stringer -type=LogLevel -trimprefix=Level"; DO NOT EDIT.

package logger

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LevelTrace-0]
	_ = x[LevelDebug-1]
	_ = x[LevelInfo-2]
	_ = x[LevelWarn-3]
	_ = x[LevelError-4]
	_ = x[LevelFatal-5]
	_ = x[LevelPanic-6]
}

const _LogLevel_name = "TraceDebugInfoWarnErrorFatalPanic"

var _LogLevel_index = [...]uint8{0, 5, 10, 14, 18, 23, 28, 33}

func (i LogLevel) String() string {
	if i < 0 || i >= LogLevel(len(_LogLevel_index)-1) {
		return "LogLevel(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LogLevel_name[_LogLevel_index[i]:_LogLevel_index[i+1]]
}
